source 'http://rubygems.org'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
group :test, :development do
  gem 'ZenTest', '~> 4.5.0'
  gem 'rake', '~> 0.9.2'
  gem 'rspec'
  gem 'ruby-debug19', '~> 0.11.6', :platforms => :mri_19
end
