#!/usr/bin/env bash
# List contributor names for the README.

names=`git log --format='[%aN](%ae)' | sort -u`
count=`echo "$names" | wc -l | sed 's/ //g'`
bullets=`echo "$names" | sed 's/^/* /'`

echo "<!-- begin \`$0\` -->"
echo
echo "Contributor count: $count"
echo
echo "$bullets"
echo
echo "<!-- end \`$0\` -->"
