#!/usr/bin/env bash
# List TODOs for the "How you can help" page

echo '<!-- begin `script/list-todos` -->'
echo
echo "As of $(date +'%Y-%m-%d'):"
echo

grep --recursive --ignore-case --files-with-matches --perl-regexp '(TODO|FIXME)' *.md |
  # More human readable, but still compatible with `gollum`
  sed 's/-/ /g' |
  # Don't include "How you can help"
  grep --invert-match --ignore-case 'How you can help' |
  # Remove extension
  sed 's/\.md$//g' |
  # Markdown-ize
  sed 's/^\(.*\)$/* [[\1]]/g'

echo
echo '<!-- end `script/list-todos` -->'
